"""Long 'channel:SH_PROXIMAL' reservoir (10 x 1 blocks — Y-flowing), uniform conditioning.

Auto-generated by ../long_setup.py.  10 blocks stacked along Y, 1 block
in X (so the final volume is 1 block wide in X).  Every block uses the
per-type training-data MEAN scalars; azimuth is fixed at 90 deg so the
channel flows along the Y axis through every block.

Raw scalars used (training mean for layer 'channel:SH_PROXIMAL'):
    ntg                    0.5099
    width_cells            13.6489
    depth_cells            6.4996
    mCHsinu                1.2248
    mFFCHprop              0.2251
    probAvulInside         0.3499
"""
import os
import time

import numpy as np
import torch

from resflow.models.unet3d import UNet3D
from resflow.methods.flow_matching import FlowMatching
from resflow.assembly import (
    BlockSpec, COND_DIM, LAYER_TYPE_TO_IDX,
    generate_big_reservoir_multi,
)


CKPT = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/flow_matching.pt')
COND_STATS = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/cond_stats.npz')
OUT_DIR = os.environ.get('RESERVOIR_OUT_DIR', 'results')

GRID_SHAPE = (10, 1)              # (ny, nx) blocks — long in Y
BLOCK_SHAPE = (64, 64, 32)
OVERLAPS = [12, 16, 24]
SEED = int(os.environ.get('RESERVOIR_SEED', 42))
N_STEPS = 50
CFG_SCALE = 3.0

LAYER_TYPE_NAME = 'channel:SH_PROXIMAL'
RAW_SCALARS = {'ntg': 0.5099, 'width_cells': 13.6489, 'depth_cells': 6.4996, 'mCHsinu': 1.2248, 'mFFCHprop': 0.2251, 'probAvulInside': 0.3499}
AZIMUTH_DEG = 90.0                # fixed — channel flows along Y


def build_grid_specs(cont_min, cont_max):
    """Uniform scalars per block, azimuth fixed at 90 deg."""
    ny, nx = GRID_SHAPE
    grid = []
    for _ in range(ny):
        row = []
        for _ in range(nx):
            row.append(BlockSpec(
                layer_idx=LAYER_TYPE_TO_IDX[LAYER_TYPE_NAME],
                azimuth_deg=AZIMUTH_DEG,
                raw_scalars=dict(RAW_SCALARS),
            ))
        grid.append(row)
    return grid


def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Device: {device}  out: {OUT_DIR}")
    print(f"Grid: {GRID_SHAPE[0]}x{GRID_SHAPE[1]} blocks of {BLOCK_SHAPE}")
    print(f"Layer type: {LAYER_TYPE_NAME}")
    print(f"Uniform raw scalars: {RAW_SCALARS}")
    print(f"Fixed azimuth: {AZIMUTH_DEG} deg")

    stats = np.load(COND_STATS, allow_pickle=True)
    cont_min, cont_max = stats['cont_min'], stats['cont_max']

    grid = build_grid_specs(cont_min, cont_max)

    model = UNet3D(in_channels=3, out_channels=1, num_cond=COND_DIM,
                   num_time_embs=1, expand_angle_idx=None).to(device)
    model.load_state_dict(torch.load(CKPT, map_location=device, weights_only=True))
    model.eval()
    method = FlowMatching(model)

    ny, nx = GRID_SHAPE
    Sx, Sy, Sz = BLOCK_SHAPE

    for overlap in OVERLAPS:
        tag = f"hard_ov{overlap:02d}"
        Tx = Sx + (nx - 1) * (Sx - overlap)
        Ty = Sy + (ny - 1) * (Sy - overlap)
        print(f"\n== {tag} == grid={ny}x{nx}, total={Tx}x{Ty}x{Sz}")
        torch.manual_seed(SEED)
        t0 = time.time()
        x_global, _ = generate_big_reservoir_multi(
            method, grid, cont_min, cont_max,
            block_shape=BLOCK_SHAPE, overlap_xy=overlap,
            n_steps=N_STEPS, cfg_scale=CFG_SCALE,
            max_batch=24, device=device,
        )
        elapsed = time.time() - t0
        volume = x_global.numpy()
        binary = (volume > 0).astype(np.int8)

        out_npz = os.path.join(OUT_DIR, f"reservoir_{tag}.npz")
        np.savez(out_npz,
                 volume=volume.astype(np.float32),
                 binary=binary,
                 mode='hard',
                 overlap=overlap,
                 block_shape=np.array(BLOCK_SHAPE),
                 ny=ny, nx=nx,
                 pure_x_indices=np.array(list(range(nx)), dtype=np.int32),
                 pure_x_layer=np.array([LAYER_TYPE_NAME] * nx, dtype=object),
                 trans_x_indices=np.array([], dtype=np.int32),
                 trans_kind='hard',
                 row_azimuths_deg=np.array(
                     [AZIMUTH_DEG] * ny, dtype=np.float32),
                 elapsed_s=elapsed)
        print(f"  saved -> {out_npz}")
        print(f"  shape={binary.shape}  NTG={binary.mean():.3f}  "
              f"{elapsed:.1f}s")


if __name__ == '__main__':
    main()
